# Generated by Django 5.0.1 on 2025-07-20 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristics', '0001_initial'),
        ('contenttypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('display_email', models.BooleanField(default=False)),
                ('display_stats', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('comment_notifications', models.BooleanField(default=True)),
                ('solution_notifications', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('class_level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='caracteristics.classlevel')),
                ('target_subjects', models.ManyToManyField(blank=True, related_name='target_users', to='caracteristics.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_grade', models.DecimalField(decimal_places=2, default=20, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='caracteristics.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Subject Grade',
                'verbose_name_plural': 'Subject Grades',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('review', 'Review'), ('viewed', 'Viewed')], default='viewed', max_length=10)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View History',
                'verbose_name_plural': 'View Histories',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
