# Generated by Django 5.0.1 on 2025-03-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appearancesettings_notificationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppearanceSettings',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
        migrations.DeleteModel(
            name='PrivacySettings',
        ),
    ]
