# Generated by Django 5.0.1 on 2025-03-31 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notificationsettings_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'View History', 'verbose_name_plural': 'View Histories'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='streak_days',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='math_notation',
            field=models.CharField(choices=[('latex', 'LaTeX'), ('ascii', 'ASCII')], default='latex', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='solution_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
