# Generated by Django 5.0.1 on 2025-04-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_alter_viewhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='math_notation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_preference',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
