# Generated by Django 5.0.1 on 2025-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_github_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='completed',
            field=models.CharField(choices=[('success', 'success'), ('review', 'review')], default='review', max_length=10),
        ),
    ]
