# Generated by Django 5.0.1 on 2025-04-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.URLField(blank=True)),
                ('favorite_subjects', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('last_activity_date', models.DateField(auto_now=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('display_email', models.BooleanField(default=False)),
                ('display_stats', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('comment_notifications', models.BooleanField(default=True)),
                ('solution_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
