# Generated by Django 5.0.1 on 2026-04-06 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristics', '0001_initial'),
        ('notebooks', '0001_initial'),
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookannotation',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='things.content'),
        ),
        migrations.AddField(
            model_name='notebookannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notebooklessonentry',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_entries', to='things.content'),
        ),
        migrations.AddField(
            model_name='notebooksection',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notebook_sections', to='caracteristics.chapter'),
        ),
        migrations.AddField(
            model_name='notebooksection',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notebooks.notebook'),
        ),
        migrations.AddField(
            model_name='notebooklessonentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_entries', to='notebooks.notebooksection'),
        ),
        migrations.AlterUniqueTogether(
            name='notebook',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='notebookannotation',
            unique_together={('user', 'lesson', 'annotation_id')},
        ),
        migrations.AlterUniqueTogether(
            name='notebooksection',
            unique_together={('notebook', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='notebooklessonentry',
            unique_together={('section', 'lesson', 'page_order')},
        ),
    ]
