# Generated by Django 5.2.17 on 2026-10-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0007_contentdailyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IAJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('import', 'Import d’un document'), ('signalement', 'Correction d’un signalement')], max_length=20)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('pret', 'Prêt à relire'), ('erreur', 'Erreur'), ('publie', 'Publié'), ('applique', 'Appliqué'), ('rejete', 'Rejeté')], db_index=True, default='en_attente', max_length=20)),
                ('etape', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('history', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ia_jobs', to='things.contentreport')),
            ],
            options={
                'db_table': 'ia_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IAFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=120)),
                ('data', models.BinaryField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ia.iajob')),
            ],
            options={
                'db_table': 'ia_file',
            },
        ),
    ]
