# Generated by Django 5.2.17 on 2026-10-07 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("comment", "Nouveau commentaire"),
                            ("reply", "Réponse à son commentaire"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                (
                    "link",
                    models.CharField(
                        help_text="Adresse de la page sur le site", max_length=200
                    ),
                ),
                (
                    "comment_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Dernier commentaire regroupé", null=True
                    ),
                ),
                ("excerpt", models.CharField(blank=True, max_length=200)),
                ("count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"], name="notif_recipient_read"
                    ),
                    models.Index(
                        fields=["recipient", "-updated_at"],
                        name="notif_recipient_recent",
                    ),
                    models.Index(fields=["target"], name="notif_target"),
                ],
            },
        ),
    ]
