# Generated by Django 5.0.1 on 2025-11-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Indexes for ViewHistory lookups (used in view tracking)
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='viewhistory_user_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['user', 'content_type', 'object_id', 'viewed_at'], name='viewhistory_user_ct_obj_time_idx'),
        ),
    ]
