# Generated by Django 5.2.7 on 2026-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_viewhistory_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='viewhistory',
            name='viewhistory_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='viewhistory',
            name='viewhistory_user_ct_obj_time_idx',
        ),
    ]
