# Generated by Django 5.2.7 on 2026-01-11 11:32

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristics', '0001_initial'),
        ('users', '0003_remove_viewhistory_viewhistory_user_ct_obj_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='current_grade',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='subjectgrade',
            name='target_grade',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_file',
            field=models.ImageField(blank=True, help_text='Uploaded avatar file', null=True, upload_to=apps.users.models.user_avatar_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Legacy URL avatar or external URL', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list, help_text='List of learning goal IDs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('visual', 'Visual'), ('practical', 'Practical'), ('theoretical', 'Theoretical'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('occasional', 'Occasional')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='caracteristics.classlevel'),
        ),
    ]
