# Generated by Django 5.0.1 on 2026-03-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristics', '0001_initial'),
        ('users', '0004_remove_userprofile_avatar_subjectgrade_current_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_class_levels',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='caracteristics.classlevel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='caracteristics.subject'),
        ),
    ]
