# Generated by Django 5.0.1 on 2026-04-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_teacher_userprofile_teacher_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='users.userprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
