# Generated by Django 5.2.17 on 2026-10-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_usagedaily"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagedaily",
            name="anon_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usagedaily",
            name="anon_visitors",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
