version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data  # Mount a volume for SQLite database
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:

volumes:
  static_volume:
  media_volume:
  sqlite_data:  # Volume for the SQLite database
