version: '3.8'

services:
  web:
    # If the image isn't available, use the local build context
    build:
      context: .
      dockerfile: Dockerfile
    # Command to run the application
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 120 --keep-alive 5 --max-requests 1000 --max-requests-jitter 50"
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    env_file:
      - .env
    networks:
      - app_network
    # Expose port 8000 to the host
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:

volumes:
  static_volume:
  media_volume:
  sqlite_data: