version: '3.8'

services:
  web:
    # This will be replaced by the ECR image during deployment
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - web
    networks:
      - app_network
    restart: always

networks:
  app_network:

volumes:
  static_volume:
  media_volume:
  sqlite_data: