# Generated by Django 5.0.1 on 2025-05-31 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_timesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timespent',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='timespent',
            name='current_session_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='timespent',
            name='last_session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timespent',
            name='resume_preference',
            field=models.CharField(choices=[('continue', 'Continuer la session précédente'), ('restart', 'Toujours recommencer'), ('ask', 'Demander à chaque fois')], default='ask', max_length=20),
        ),
        migrations.AddField(
            model_name='timespent',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
