# Generated by Django 5.0.1 on 2025-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_remove_timespent_time_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timespent',
            name='resume_preference',
        ),
    ]
