# Generated by Django 5.2.7 on 2026-01-11 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(db_index=True, max_length=200)),
                ('variant_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('traffic_percentage', models.IntegerField(default=50)),
                ('impressions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_name', 'variant_name'],
                'unique_together': {('test_name', 'variant_name')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('interactions_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('time_on_page', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'path'], name='logging_pag_timesta_01353d_idx'), models.Index(fields=['session_id', '-timestamp'], name='logging_pag_session_062ec6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('click', 'Click'), ('hover', 'Hover'), ('scroll', 'Scroll'), ('form_submit', 'Form Submit'), ('search', 'Search'), ('filter', 'Filter'), ('sort', 'Sort'), ('video_play', 'Video Play'), ('video_pause', 'Video Pause'), ('tab_switch', 'Tab Switch'), ('modal_open', 'Modal Open'), ('modal_close', 'Modal Close'), ('other', 'Other')], db_index=True, max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=200, null=True)),
                ('element_class', models.CharField(blank=True, max_length=200, null=True)),
                ('element_text', models.CharField(blank=True, max_length=500, null=True)),
                ('element_position', models.JSONField(blank=True, null=True)),
                ('page_path', models.CharField(db_index=True, max_length=500)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'interaction_type'], name='logging_use_timesta_f0120a_idx'), models.Index(fields=['page_path', 'element_id'], name='logging_use_page_pa_2e2c15_idx'), models.Index(fields=['variant', '-timestamp'], name='logging_use_variant_29b995_idx')],
            },
        ),
    ]
