# Generated by Django 5.0.1 on 2026-05-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0002_concoursexamstats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='concourscomment',
            new_name='concours_co_target__5841f2_idx',
            old_name='concours_co_target__d2f2b1_idx',
        ),
        migrations.RenameIndex(
            model_name='concoursexam',
            new_name='concours_co_concour_71f787_idx',
            old_name='concours_co_concour_e9437b_idx',
        ),
        migrations.RenameIndex(
            model_name='concourstip',
            new_name='concours_co_subject_8344b2_idx',
            old_name='concours_co_subject_8d211b_idx',
        ),
        migrations.RenameIndex(
            model_name='concourstip',
            new_name='concours_co_subfiel_70d12e_idx',
            old_name='concours_co_subfiel_2c8e44_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationanswer',
            new_name='concours_si_session_5e15a1_idx',
            old_name='concours_si_session_77c4f9_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationanswer',
            new_name='concours_si_session_d29326_idx',
            old_name='concours_si_session_3a8e22_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationsession',
            new_name='concours_si_user_id_e65293_idx',
            old_name='concours_si_user_id_4d6e91_idx',
        ),
        migrations.RenameIndex(
            model_name='simulationsession',
            new_name='concours_si_user_id_c4aef8_idx',
            old_name='concours_si_user_id_7b2c10_idx',
        ),
    ]
