# Generated by Django 5.0.1 on 2026-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0003_rename_concours_co_target__d2f2b1_idx_concours_co_target__5841f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concoursexam',
            name='json_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
