# Generated by Django 5.0.1 on 2025-06-01 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notebookannotation'),
        ('things', '0004_remove_exam_national_date_exam_national_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notebookannotation',
            name='unique_user_lesson_annotation',
        ),
        migrations.AlterUniqueTogether(
            name='notebookannotation',
            unique_together={('user', 'lesson', 'annotation_id')},
        ),
    ]
