# Generated by Django 5.0.1 on 2025-05-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristics', '0001_initial'),
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapters',
            field=models.ManyToManyField(related_name='exams', to='caracteristics.chapter'),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_levels',
            field=models.ManyToManyField(related_name='exams', to='caracteristics.classlevel'),
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='is_national_exam',
            field=models.BooleanField(default=False, help_text='Indicates if this exam is a national exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='national_date',
            field=models.DateField(blank=True, help_text='Date of the exam if it is a national exam', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subfields',
            field=models.ManyToManyField(related_name='exams', to='caracteristics.subfield'),
        ),
        migrations.AddField(
            model_name='exam',
            name='theorems',
            field=models.ManyToManyField(related_name='exams', to='caracteristics.theorem'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='caracteristics.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='exam',
            table=None,
        ),
    ]
