# Generated by Django 5.1.6 on 2025-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='subfield',
            field=models.ManyToManyField(related_name='exercises', to='things.subfield'),
        ),
    ]
