# Generated by Django 5.0.1 on 2025-05-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_comment_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='national_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='national_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of the exam if it is a national exam (YYYY format)', null=True),
        ),
    ]
