# Generated by Django 5.0.1 on 2025-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_complete_evaluate_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('review', 'review')], max_length=10),
        ),
    ]
