# Generated by Django 5.0.1 on 2025-11-07 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_taxonomytimespent'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomytimespent',
            name='exam_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='taxonomytimespent',
            name='exercise_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='taxonomytimespent',
            name='lesson_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
