# Generated by Django 5.0.1 on 2025-11-07 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0003_taxonomytimespent_exam_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studytimetracker',
            index=models.Index(fields=['user', 'recorded_at'], name='interaction_user_id_61cac7_idx'),
        ),
        migrations.AddIndex(
            model_name='studytimetracker',
            index=models.Index(fields=['user', 'content_type'], name='interaction_user_id_120936_idx'),
        ),
    ]
