# Generated by Django 5.0.1 on 2025-11-07 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0004_studytimetracker_interaction_user_id_61cac7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytimetracker',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='studytimetracker',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
