# Generated by Django 5.0.1 on 2025-11-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_alter_studytimetracker_recorded_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSpent',
        ),
    ]
