# Generated by Django 5.0.1 on 2025-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_remove_timespent'),
    ]

    operations = [
        # Indexes for Vote lookups (user + content_type + object_id)
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='vote_user_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='vote_ct_obj_idx'),
        ),

        # Indexes for Save lookups
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='save_user_ct_obj_idx'),
        ),

        # Indexes for Complete lookups
        migrations.AddIndex(
            model_name='complete',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='complete_user_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='complete',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='complete_ct_obj_status_idx'),
        ),

        # Indexes for TimeSession lookups
        migrations.AddIndex(
            model_name='timesession',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='timesession_user_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='timesession',
            index=models.Index(fields=['user', 'created_at'], name='timesession_user_created_idx'),
        ),

        # Indexes for SolutionView lookups
        migrations.AddIndex(
            model_name='solutionview',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='solutionview_user_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='solutionview',
            index=models.Index(fields=['content_type', 'object_id'], name='solutionview_ct_obj_idx'),
        ),

        # Indexes for SolutionMatch lookups
        migrations.AddIndex(
            model_name='solutionmatch',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='solutionmatch_user_ct_obj_idx'),
        ),

        # Indexes for StudyTimeTracker lookups
        migrations.AddIndex(
            model_name='studytimetracker',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='studytime_user_ct_obj_idx'),
        ),

        # Indexes for TaxonomyTimeSpent lookups
        migrations.AddIndex(
            model_name='taxonomytimespent',
            index=models.Index(fields=['user', 'taxonomy_type'], name='taxonomy_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomytimespent',
            index=models.Index(fields=['user', 'taxonomy_type', 'content_type', 'object_id'], name='taxonomy_full_idx'),
        ),
    ]
