# Generated by Django 5.2.7 on 2026-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complete',
            name='complete_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='complete',
            name='complete_ct_obj_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='save',
            name='save_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='solutionmatch',
            name='solutionmatch_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='solutionview',
            name='solutionview_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='solutionview',
            name='solutionview_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='studytimetracker',
            name='studytime_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxonomytimespent',
            name='taxonomy_user_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxonomytimespent',
            name='taxonomy_full_idx',
        ),
        migrations.RemoveIndex(
            model_name='timesession',
            name='timesession_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='timesession',
            name='timesession_user_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='vote_user_ct_obj_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='vote_ct_obj_idx',
        ),
    ]
