# Generated by Django 5.0.1 on 2026-01-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_remove_complete_complete_user_ct_obj_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing display ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing display ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-incrementing display ID', null=True, unique=True),
        ),
    ]
