# Generated by Django 5.2.7 on 2026-01-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_exam_exam_id_exercise_exercise_id_lesson_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='save',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='timesession',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vote',
            name='object_id',
            field=models.CharField(max_length=64),
        ),
    ]
