# Generated by Django 5.0.1 on 2026-01-27 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0010_alter_complete_object_id_alter_evaluate_object_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('question_path', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('review', 'Review'), ('failed', 'Failed')], max_length=10)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='interaction_user_id_f54901_idx'), models.Index(fields=['content_type', 'object_id'], name='interaction_content_8d587f_idx')],
                'unique_together': {('user', 'content_type', 'object_id', 'question_path')},
            },
        ),
    ]
