# Generated by Django 5.0.1 on 2026-01-28 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0012_questionprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('image', models.ImageField(max_length=500, upload_to='ai_corrections/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ai_provider', models.CharField(default='openai', max_length=20)),
                ('ai_model', models.CharField(default='gpt-4-vision-preview', max_length=50)),
                ('score_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.TextField(blank=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_correction',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='ai_correcti_user_id_85b62a_idx'), models.Index(fields=['submitted_at'], name='ai_correcti_submitt_2d6118_idx')],
            },
        ),
    ]
