# Generated by Django 5.0.1 on 2026-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0013_aicorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicorrection',
            name='conversation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicorrection',
            name='language',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='aicorrection',
            name='pedagogical_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aicorrection',
            name='submission_state',
            field=models.CharField(choices=[('pre_submission', 'Pré-soumission'), ('submitted', 'Soumis'), ('discussed', 'Discuté')], default='pre_submission', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicorrection',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='ai_corrections/%Y/%m/'),
        ),
    ]
