# Generated by Django 5.0.1 on 2026-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0014_add_pedagogical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionprogress',
            name='solution_validation',
            field=models.CharField(blank=True, choices=[('compatible', 'Compatible'), ('different', 'Different'), ('not-understood', 'Not Understood')], max_length=20, null=True),
        ),
    ]
