# Generated by Django 5.2.17 on 2026-10-08 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caracteristics", "0002_school"),
        ("interactions", "0019_studytimeday"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ds", "DS"),
                            ("controle", "Contrôle"),
                            ("blanc", "Examen blanc"),
                        ],
                        default="ds",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Note sur 20",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("mock_ids", models.JSONField(blank=True, default=list)),
                ("mock_started_at", models.DateTimeField(blank=True, null=True)),
                ("mock_done_at", models.DateTimeField(blank=True, null=True)),
                ("mock_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapters",
                    models.ManyToManyField(
                        related_name="upcoming_tests", to="caracteristics.chapter"
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="caracteristics.classlevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="caracteristics.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcoming_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="upcomingtest_user_date")
                ],
            },
        ),
    ]
