# Generated by Django 5.2.17 on 2026-10-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0020_upcomingtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionprogress",
            name="source",
            field=models.CharField(
                choices=[
                    ("question", "Question par question"),
                    ("tout", "Tout réussi"),
                    ("apres_solution", "Après la solution"),
                    ("rattrapage", "Bandeau de rattrapage"),
                ],
                default="question",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="timesession",
            name="max_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timesession",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
