# Generated by Django 5.0.1 on 2026-04-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classroommembership',
            new_name='classrooms__student_4a9d4d_idx',
            old_name='classrooms__student_idx',
        ),
        migrations.RenameIndex(
            model_name='classroommembership',
            new_name='classrooms__classro_47241f_idx',
            old_name='classrooms__classr_idx',
        ),
    ]
