# Generated by Django 5.0.1 on 2026-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_tdlist_tdlistitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tdlist',
            new_name='classrooms__classro_e26425_idx',
            old_name='classrooms__td_classr_idx',
        ),
        migrations.RenameIndex(
            model_name='tdlist',
            new_name='classrooms__due_dat_c8ddd5_idx',
            old_name='classrooms__td_due_idx',
        ),
    ]
