# Generated by Django 5.2.17 on 2026-10-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skilliq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillassessment",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="skillassessment",
            name="previous_max",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillassessment",
            name="previous_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
