# Generated by Django 5.0.1 on 2026-04-06 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('exercise', 'Exercise'), ('lesson', 'Lesson'), ('exam', 'Exam')], db_index=True, max_length=10)),
                ('display_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10, null=True)),
                ('is_national_exam', models.BooleanField(default=False)),
                ('national_year', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('chapters', models.ManyToManyField(blank=True, related_name='content_items', to='caracteristics.chapter')),
                ('class_levels', models.ManyToManyField(related_name='content_items', to='caracteristics.classlevel')),
                ('subfields', models.ManyToManyField(blank=True, related_name='content_items', to='caracteristics.subfield')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='caracteristics.subject')),
                ('theorems', models.ManyToManyField(blank=True, related_name='content_items', to='caracteristics.theorem')),
            ],
            options={
                'db_table': 'things_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='things.comment')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='things.content')),
            ],
            options={
                'db_table': 'things_comment',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='things.content')),
            ],
            options={
                'db_table': 'things_solution',
            },
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('type', 'display_id'), name='unique_display_id_per_type'),
        ),
    ]
