# Generated by Django 5.0.1 on 2026-04-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='content',
            name='version',
        ),
    ]
