# Generated by Django 5.0.1 on 2026-07-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_remove_content_structure_remove_content_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='json_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
