# Generated by Django 5.2.17 on 2026-09-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_content_json_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_solutions', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_solutions', to='things.content')),
            ],
            options={
                'db_table': 'things_proposedsolution',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_item', '-created_at'], name='things_prop_content_b8226d_idx')],
            },
        ),
    ]
