# Generated by Django 5.2.17 on 2026-09-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_proposedsolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
    ]
