# Generated by Django 5.2.17 on 2026-10-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_contentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='things.content')),
            ],
            options={
                'db_table': 'things_contentdailyview',
                'indexes': [models.Index(fields=['date'], name='dailyview_date')],
                'constraints': [models.UniqueConstraint(fields=('content', 'date'), name='unique_daily_view')],
            },
        ),
    ]
