# Generated by Django 5.2.17 on 2026-10-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0009_rattacher_reponses"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdailyview",
            name="anon_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
