# Generated by Django 5.2.17 on 2026-10-10 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remplir_search_text(apps, schema_editor):
    from apps.things.search_text import build_search_text
    Content = apps.get_model('things', 'Content')
    batch = []
    for c in Content.objects.only('id', 'title', 'json_content').iterator(chunk_size=200):
        c.search_text = build_search_text(c.title, c.json_content)
        batch.append(c)
        if len(batch) >= 200:
            Content.objects.bulk_update(batch, ['search_text'])
            batch = []
    if batch:
        Content.objects.bulk_update(batch, ['search_text'])


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0010_anonymes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="search_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="DifficultyFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "felt",
                    models.CharField(
                        choices=[
                            ("easier", "Plus facile qu’annoncé"),
                            ("as_said", "Comme annoncé"),
                            ("harder", "Plus difficile qu’annoncé"),
                        ],
                        max_length=8,
                    ),
                ),
                ("declared", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_feedback",
                        to="things.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difficulty_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "things_difficultyfeedback",
                "indexes": [
                    models.Index(fields=["content"], name="difficultyfeedback_content")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content"), name="unique_difficulty_feedback"
                    )
                ],
            },
        ),
        migrations.RunPython(remplir_search_text, migrations.RunPython.noop),
    ]
